import { StyleSheet } from "react-native";
import type { Theme } from "../../theme/theme";
import { homePalette } from "../home/homePalette";

export function comparePalette(theme: Theme) {
  const p = homePalette(theme);
  const light = theme.name === "light";
  return {
    ...p,
    // Chart series: distinct hues that each clear 3:1 against their chart surface.
    series: light ? ["#0F766E", "#1D4ED8", "#B45309", "#7C3AED", "#BE123C"] : ["#2DD4BF", "#60A5FA", "#FBBF24", "#C4B5FD", "#FDA4AF"],
    rise: light ? "#B42318" : "#FDA4AF",
  };
}

export type ComparePalette = ReturnType<typeof comparePalette>;

export const makeCompareStyles = (theme: Theme) => {
  const p = comparePalette(theme);
  const large = theme.m.isLargeText;
  const xl = theme.m.isXLText;
  const f = theme.m.f;

  return StyleSheet.create({
    statusRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", columnGap: 8, rowGap: 2 },
    dot: { width: 8, height: 8, borderRadius: 4 },
    statusText: { flexShrink: 1, color: p.inkSoft, fontSize: f(13), lineHeight: f(19), fontWeight: "700" },
    retry: { minHeight: 44, justifyContent: "center", paddingHorizontal: 4 },
    retryText: { color: p.accent, fontSize: f(13), fontWeight: "900", textDecorationLine: "underline" },

    // Verdict
    deck: {
      borderRadius: 24,
      backgroundColor: p.deck,
      borderWidth: theme.name === "light" ? 1.5 : 1,
      borderColor: p.deckBorder,
      padding: 8,
      gap: 8,
      shadowColor: "#102033",
      shadowOpacity: p.shadow,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: theme.name === "light" ? 2 : 0,
    },
    module: {
      borderRadius: 18,
      backgroundColor: p.module,
      paddingHorizontal: theme.m.s(18),
      paddingTop: theme.m.s(14),
      paddingBottom: theme.m.s(16),
      gap: 10,
      borderLeftWidth: theme.name === "dark" ? 3 : 0,
      borderLeftColor: p.accent,
    },
    kicker: { color: p.moduleSoft, fontSize: f(12), fontWeight: "900", letterSpacing: 1.6, textTransform: "uppercase" },
    ends: { flexDirection: large ? "column" : "row", gap: large ? 12 : 14 },
    end: { flex: large ? undefined : 1, minWidth: 0, gap: 2 },
    endLabel: { flexDirection: "row", alignItems: "center", gap: 6 },
    endLabelText: { color: p.moduleSoft, fontSize: f(12), fontWeight: "800", letterSpacing: 0.6, textTransform: "uppercase" },
    endCountry: { color: p.moduleText, fontSize: f(18), lineHeight: f(24), fontWeight: "900" },
    endPrice: { color: p.moduleText, fontSize: f(16), fontWeight: "800", fontVariant: ["tabular-nums"] },
    moduleRule: { height: 1, backgroundColor: p.moduleRule },
    spreadLabel: { color: p.moduleSoft, fontSize: f(12), fontWeight: "800", letterSpacing: 0.6, textTransform: "uppercase" },
    spreadRow: { flexDirection: "row", alignItems: "flex-end", flexWrap: "wrap", columnGap: 6 },
    spreadValue: {
      color: p.moduleText,
      fontSize: f(40),
      lineHeight: f(46),
      fontWeight: "900",
      letterSpacing: -1,
      fontVariant: ["tabular-nums"],
      includeFontPadding: false,
    },
    spreadUnit: { color: p.moduleSoft, fontSize: f(16), lineHeight: f(24), fontWeight: "800" },
    moduleBody: { color: p.moduleSoft, fontSize: f(14), lineHeight: f(20), fontWeight: "700" },
    headline: { color: p.moduleText, fontSize: f(22), lineHeight: f(28), fontWeight: "900" },

    // Board
    board: {
      borderRadius: 22,
      backgroundColor: p.deck,
      borderWidth: 1,
      borderColor: p.chipBorder,
      paddingHorizontal: theme.m.s(14),
      paddingTop: theme.m.s(12),
      paddingBottom: theme.m.s(10),
    },
    boardHeader: {
      flexDirection: xl ? "column" : "row",
      alignItems: xl ? "flex-start" : "center",
      justifyContent: "space-between",
      columnGap: 12,
      rowGap: 2,
      paddingBottom: 8,
    },
    boardKicker: { color: p.inkSoft, fontSize: f(12), fontWeight: "900", letterSpacing: 1.4, textTransform: "uppercase" },
    boardCount: { color: p.inkSoft, fontSize: f(13), fontWeight: "700" },
    lane: { paddingVertical: theme.m.s(12), gap: 8, borderTopWidth: 1, borderTopColor: p.rule },
    laneTop: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
    position: {
      minWidth: 30,
      minHeight: 30,
      paddingHorizontal: 6,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1.5,
      borderColor: p.chipBorder,
    },
    positionCheapest: { borderColor: p.good, backgroundColor: p.accentSoft },
    positionText: { color: p.ink, fontSize: f(13), fontWeight: "900", fontVariant: ["tabular-nums"] },
    laneMain: { flex: 1, minWidth: 0, gap: 6 },
    laneHead: { flexDirection: large ? "column" : "row", alignItems: large ? "flex-start" : "flex-start", justifyContent: "space-between", columnGap: 10, rowGap: 4 },
    laneName: { flexShrink: 1, color: p.ink, fontSize: f(17), lineHeight: f(23), fontWeight: "800" },
    lanePrices: { alignItems: large ? "flex-start" : "flex-end" },
    lanePrice: { color: p.ink, fontSize: f(18), lineHeight: f(24), fontWeight: "900", fontVariant: ["tabular-nums"] },
    laneSecondary: { color: p.inkSoft, fontSize: f(13), lineHeight: f(18), fontWeight: "700", fontVariant: ["tabular-nums"] },
    trackRow: { flexDirection: xl ? "column" : "row", alignItems: xl ? "stretch" : "center", gap: xl ? 6 : 12 },
    track: { flex: xl ? undefined : 1, height: 18, justifyContent: "center" },
    trackBase: { height: 4, borderRadius: 2, backgroundColor: p.rule },
    trackFill: { position: "absolute", left: 0, height: 4, borderRadius: 2, backgroundColor: p.lane },
    trackDot: { position: "absolute", width: 16, height: 16, marginLeft: -8, borderRadius: 8, borderWidth: 3, backgroundColor: p.deck },
    gapTag: { flexDirection: "row", alignItems: "center", gap: 5 },
    gapText: { color: p.ink, fontSize: f(14), fontWeight: "800", fontVariant: ["tabular-nums"] },
    gapTextCheapest: { color: p.good },
    laneMeta: { flexDirection: large ? "column" : "row", flexWrap: "wrap", columnGap: 14, rowGap: 4 },
    metaItem: { flexDirection: "row", alignItems: "center", gap: 5, maxWidth: "100%" },
    metaText: { flexShrink: 1, color: p.inkSoft, fontSize: f(13), lineHeight: f(19), fontWeight: "700" },
    removeButton: { width: 48, height: 48, marginTop: -10, marginRight: -8, alignItems: "center", justifyContent: "center", borderRadius: 14 },

    // Add / unlock slot
    slot: {
      marginTop: 4,
      minHeight: 56,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 16,
      borderWidth: 1,
      borderStyle: "dashed",
      borderColor: p.lane,
    },
    slotLocked: { borderStyle: "solid", borderColor: p.chipBorder, backgroundColor: p.accentSoft },
    slotIcon: { width: 36, height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: p.pressed },
    slotCopy: { flex: 1, minWidth: 0 },
    slotTitle: { color: p.ink, fontSize: f(16), lineHeight: f(22), fontWeight: "800" },
    slotDetail: { color: p.inkSoft, fontSize: f(13), lineHeight: f(19), fontWeight: "600" },
    notice: { marginTop: 10, padding: 12, gap: 10, borderRadius: 16, backgroundColor: p.pressed },
    noticeRow: { flexDirection: "row", alignItems: "flex-start", gap: 8 },
    noticeText: { flex: 1, color: p.ink, fontSize: f(14), lineHeight: f(20), fontWeight: "700" },
    noticeActions: { flexDirection: large ? "column" : "row", flexWrap: "wrap", gap: 8 },

    // Buttons
    primaryButton: {
      flexGrow: 1,
      minHeight: 52,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingHorizontal: 18,
      paddingVertical: 12,
      borderRadius: 16,
      backgroundColor: p.accent,
    },
    primaryText: { flexShrink: 1, color: p.onAccent, fontSize: f(16), lineHeight: f(21), fontWeight: "900", textAlign: "center" },
    secondaryButton: {
      flexGrow: 1,
      minHeight: 52,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 16,
      backgroundColor: p.chip,
      borderWidth: 1,
      borderColor: p.chipBorder,
    },
    secondaryText: { flexShrink: 1, color: p.ink, fontSize: f(16), lineHeight: f(21), fontWeight: "800", textAlign: "center" },
    disabled: { opacity: 0.45 },

    // Empty
    state: { padding: theme.m.s(20), gap: 12, borderRadius: 22, backgroundColor: p.deck, borderWidth: 1, borderColor: p.chipBorder },
    stateIcon: { width: 52, height: 52, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: p.accentSoft },
    stateTitle: { color: p.ink, fontSize: f(20), lineHeight: f(26), fontWeight: "900" },
    stateBody: { color: p.inkSoft, fontSize: f(15), lineHeight: f(22), fontWeight: "600" },
    picksLabel: { marginTop: 4, color: p.inkSoft, fontSize: f(12), fontWeight: "900", letterSpacing: 1.2, textTransform: "uppercase" },
    picks: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    pick: {
      minHeight: 48,
      maxWidth: "100%",
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: p.chip,
      borderWidth: 1,
      borderColor: p.chipBorder,
    },
    pickText: { flexShrink: 1, color: p.ink, fontSize: f(15), fontWeight: "800" },

    // Skeleton
    skeletonModule: { minHeight: 190, justifyContent: "flex-end", gap: 12 },
    skeletonBar: { height: 16, borderRadius: 8, backgroundColor: p.moduleRule },
    skeletonRowBar: { height: 14, borderRadius: 7, backgroundColor: p.rule },

    // Trend
    trendCard: { borderRadius: 22, backgroundColor: p.deck, borderWidth: 1, borderColor: p.chipBorder, padding: theme.m.s(16), gap: 12 },
    trendHeader: { flexDirection: xl ? "column" : "row", alignItems: xl ? "stretch" : "center", justifyContent: "space-between", gap: 10 },
    trendTitle: { flex: xl ? undefined : 1, color: p.ink, fontSize: f(17), lineHeight: f(23), fontWeight: "900" },
    period: { flexDirection: "row", padding: 3, gap: 3, borderRadius: 14, backgroundColor: p.pressed },
    periodItem: { flex: xl ? 1 : undefined },
    periodButton: { minWidth: 64, minHeight: 48, paddingHorizontal: 12, alignItems: "center", justifyContent: "center", borderRadius: 11 },
    periodActive: { backgroundColor: p.chip, borderWidth: 1, borderColor: p.chipBorder },
    periodText: { color: p.inkSoft, fontSize: f(14), fontWeight: "800" },
    periodTextActive: { color: p.ink, fontWeight: "900" },
    trendSummary: { color: p.ink, fontSize: f(15), lineHeight: f(22), fontWeight: "700" },
    trendRange: { color: p.inkSoft, fontSize: f(13), lineHeight: f(19), fontWeight: "700" },
    chart: { height: 150, borderRadius: 14, backgroundColor: p.pressed, overflow: "hidden" },
    axis: { flexDirection: "row", justifyContent: "space-between", gap: 12 },
    axisText: { color: p.inkSoft, fontSize: f(12), fontWeight: "700" },
    legend: { gap: 4 },
    legendRow: { minHeight: 44, flexDirection: "row", alignItems: "center", flexWrap: "wrap", columnGap: 10, rowGap: 2, paddingVertical: 4 },
    legendName: { flexGrow: 1, flexShrink: 1, color: p.ink, fontSize: f(15), lineHeight: f(21), fontWeight: "800" },
    legendValue: { color: p.inkSoft, fontSize: f(14), lineHeight: f(20), fontWeight: "700", fontVariant: ["tabular-nums"] },

    // Saved comparisons sheet
    sheetBody: { gap: 10, paddingBottom: 8 },
    sheetLabel: { marginTop: 4, color: p.inkSoft, fontSize: f(12), fontWeight: "900", letterSpacing: 1.2, textTransform: "uppercase" },
    input: {
      minHeight: 52,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 16,
      color: p.ink,
      fontSize: f(16),
      fontWeight: "700",
      backgroundColor: p.pressed,
      borderWidth: 1,
      borderColor: p.chipBorder,
    },
    helper: { color: p.inkSoft, fontSize: f(13), lineHeight: f(19), fontWeight: "600" },
    sheetDivider: { height: 1, marginVertical: 8, backgroundColor: p.rule },
    setRow: { paddingVertical: 12, gap: 10, borderTopWidth: 1, borderTopColor: p.rule },
    setTop: { flexDirection: large ? "column" : "row", alignItems: large ? "stretch" : "center", gap: 10 },
    setCopy: { flex: large ? undefined : 1, minWidth: 0, gap: 2 },
    setName: { color: p.ink, fontSize: f(16), lineHeight: f(22), fontWeight: "800" },
    setCountries: { color: p.inkSoft, fontSize: f(14), lineHeight: f(20), fontWeight: "600" },
    setActions: { flexDirection: "row", gap: 8 },
    setOpen: {
      minHeight: 48,
      flexGrow: large ? 1 : 0,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingHorizontal: 16,
      borderRadius: 14,
      backgroundColor: p.accentSoft,
      borderWidth: 1,
      borderColor: theme.name === "light" ? "rgba(15,118,110,0.22)" : "rgba(45,212,191,0.24)",
    },
    setOpenText: { color: p.accent, fontSize: f(15), fontWeight: "900" },
    setDelete: { width: 48, height: 48, alignItems: "center", justifyContent: "center", borderRadius: 14, borderWidth: 1, borderColor: p.chipBorder },
    emptySets: { paddingVertical: 12, color: p.inkSoft, fontSize: f(14), lineHeight: f(20), fontWeight: "600" },
  });
};

export type CompareStyles = ReturnType<typeof makeCompareStyles>;
