import { StyleSheet } from "react-native";
import type { Theme } from "../../theme/theme";

export const makeCompareStyles = (theme: Theme) => StyleSheet.create({
  wrap: { gap: theme.m.s(14) },
  hero: { padding: theme.m.s(18), borderRadius: 28, gap: 16, backgroundColor: theme.name === "light" ? "#EAF5F2" : "#0C3437", borderWidth: 1, borderColor: theme.name === "light" ? "rgba(15,118,110,0.14)" : "rgba(45,212,191,0.20)" },
  heroTop: { flexDirection: "row", alignItems: "center", gap: 14 },
  heroCopy: { flex: 1, minWidth: 0 },
  kicker: { color: theme.colors.primary, fontSize: theme.m.f(10), fontWeight: "900", textTransform: "uppercase", letterSpacing: 1 },
  heroTitle: { marginTop: 5, color: theme.colors.text, fontSize: theme.m.f(26), lineHeight: theme.m.f(31), fontWeight: "900" },
  heroSubtitle: { marginTop: 4, color: theme.colors.subText, fontSize: theme.m.f(12), fontWeight: "800" },
  heroIcon: { width: 68, height: 68, borderRadius: 25, alignItems: "center", justifyContent: "center", backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  metrics: { flexDirection: theme.m.isLargeText ? "column" : "row", gap: 8 },
  metric: { flex: 1, minHeight: 70, padding: 11, borderRadius: 18, justifyContent: "space-between", backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  metricValue: { color: theme.colors.text, fontSize: theme.m.f(16), fontWeight: "900" },
  metricLabel: { color: theme.colors.muted, fontSize: theme.m.f(10), fontWeight: "800" },
  actionRow: { flexDirection: "row", gap: 10 },
  secondaryButton: { minHeight: 50, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, paddingHorizontal: 15, borderRadius: 18, backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  secondaryButtonText: { color: theme.colors.text, fontSize: theme.m.f(12), fontWeight: "900" },
  primaryButton: { flex: 1, minHeight: 50, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, paddingHorizontal: 15, borderRadius: 18, backgroundColor: theme.colors.primary },
  primaryButtonText: { color: theme.colors.primaryText, fontSize: theme.m.f(13), fontWeight: "900" },
  disabled: { opacity: 0.42 },
  limitNote: { minHeight: 42, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 12, borderRadius: 15, backgroundColor: theme.colors.surfaceMuted },
  limitText: { flex: 1, color: theme.colors.muted, fontSize: theme.m.f(11), lineHeight: theme.m.f(16), fontWeight: "700" },
  sectionTitle: { marginBottom: 9, color: theme.colors.text, fontSize: theme.m.f(15), fontWeight: "900" },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  countryChip: { minHeight: 44, maxWidth: "100%", flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 11, borderRadius: 999, backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  chipFlag: { fontSize: 16 },
  chipText: { maxWidth: 130, color: theme.colors.text, fontSize: theme.m.f(11), fontWeight: "800" },
  empty: { alignItems: "center", padding: 24, borderRadius: 25, backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  emptyIcon: { width: 58, height: 58, borderRadius: 22, alignItems: "center", justifyContent: "center", backgroundColor: theme.colors.accentSoft },
  emptyTitle: { marginTop: 13, color: theme.colors.text, fontSize: theme.m.f(17), fontWeight: "900", textAlign: "center" },
  emptyText: { marginTop: 6, color: theme.colors.muted, fontSize: theme.m.f(12), lineHeight: theme.m.f(18), fontWeight: "700", textAlign: "center" },
  emptyButton: { marginTop: 16, minHeight: 50, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 18, borderRadius: 18, backgroundColor: theme.colors.primary },
  rows: { gap: 10 },
  row: { padding: 14, borderRadius: 22, gap: 11, backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  bestRow: { borderColor: theme.name === "light" ? "rgba(15,118,110,0.38)" : "rgba(45,212,191,0.42)", backgroundColor: theme.name === "light" ? "#F2FAF7" : "#103136" },
  rowTop: { flexDirection: "row", alignItems: "center", gap: 10 },
  rank: { width: 43, height: 43, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: theme.colors.surfaceMuted },
  bestRank: { backgroundColor: theme.colors.accentSoft },
  rankText: { color: theme.colors.text, fontSize: theme.m.f(12), fontWeight: "900" },
  rowCopy: { flex: 1, minWidth: 0 },
  country: { color: theme.colors.text, fontSize: theme.m.f(14), fontWeight: "900" },
  secondary: { marginTop: 4, color: theme.colors.muted, fontSize: theme.m.f(10), fontWeight: "700" },
  priceCopy: { alignItems: "flex-end" },
  price: { color: theme.colors.text, fontSize: theme.m.f(16), fontWeight: "900" },
  bestText: { marginTop: 3, color: theme.colors.success, fontSize: theme.m.f(10), fontWeight: "900" },
  diffText: { marginTop: 3, color: theme.colors.warning, fontSize: theme.m.f(10), fontWeight: "900" },
  track: { height: 6, borderRadius: 999, overflow: "hidden", backgroundColor: theme.colors.surfaceMuted },
  trackFill: { height: "100%", borderRadius: 999, backgroundColor: theme.colors.primary },
  deltaRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  deltaLabel: { color: theme.colors.muted, fontSize: theme.m.f(10), fontWeight: "700" },
  delta: { color: theme.colors.muted, fontSize: theme.m.f(10), fontWeight: "800", textAlign: "right" },
  deltaUp: { color: theme.colors.danger },
  deltaDown: { color: theme.colors.success },
  sheetContent: { gap: 10, paddingBottom: 8 },
  sheetLabel: { color: theme.colors.text, fontSize: theme.m.f(13), fontWeight: "900" },
  input: { minHeight: 50, paddingHorizontal: 14, borderRadius: 17, color: theme.colors.text, fontSize: theme.m.f(14), fontWeight: "700", backgroundColor: theme.colors.surfaceMuted, borderWidth: 1, borderColor: theme.colors.border },
  validation: { color: theme.colors.warning, fontSize: theme.m.f(11), fontWeight: "700" },
  saveButton: { minHeight: 50, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, borderRadius: 18, backgroundColor: theme.colors.primary },
  sheetDivider: { height: 1, marginVertical: 6, backgroundColor: theme.colors.border },
  setRow: { minHeight: 66, flexDirection: "row", alignItems: "center", gap: 8, padding: 10, borderRadius: 18, backgroundColor: theme.colors.surfaceMuted },
  setCopy: { flex: 1, minWidth: 0 },
  setName: { color: theme.colors.text, fontSize: theme.m.f(13), fontWeight: "900" },
  setCountries: { marginTop: 3, color: theme.colors.muted, fontSize: theme.m.f(10), lineHeight: theme.m.f(14), fontWeight: "700" },
  setAction: { width: 48, height: 48, borderRadius: 17, alignItems: "center", justifyContent: "center", backgroundColor: theme.colors.surfaceRaised },
  emptySets: { paddingVertical: 18, color: theme.colors.muted, fontSize: theme.m.f(12), fontWeight: "700", textAlign: "center" },
});
