export const commercialCopy = {
  en: {
    about: "Karburanti Sot is maintained independently in Tirana. Display advertising and clearly labelled travel affiliate links may fund the free service. Commercial arrangements do not influence fuel prices, rankings, or editorial conclusions.",
    status: "This website may display Google AdSense advertising and labelled rental affiliate links when configured. Advertising consent choices are managed through Google's Privacy & messaging service. The fuel tools remain free to use.",
    ads: "Google AdSense and its partners may use cookies or device identifiers for advertising and measurement. On eligible English pages, ad units wait for Google's certified Privacy & messaging service to report that consent choices are ready. Google applies those choices to ad serving, including restrictions when you decline. Where required, including the EEA, UK and Switzerland, the consent message lets you consent, decline or manage options. Reopen it using Privacy and cookie settings in the footer. If a browser blocks the service, ads may not load. We retain publisher verification metadata; it does not itself load an advertising script.",
    analytics: "When enabled, Cloudflare Web Analytics measures page views, referring sites, countries, devices and page performance. We do not add analytics cookies or personal identifiers. Browser blocking and service sampling can limit these reports. Cloudflare processes requests under its own privacy policy. We do not collect rental payment details or operate a customer account system.",
    affiliate: "Labelled DiscoverCars links contain referral and campaign identifiers. If you click one, the provider receives the request and may use its own cookies or identifiers to attribute a booking under its privacy terms. We may receive a commission on eligible completed rentals and view referral and commission reports. No affiliate tracking widget is loaded on our website. Shared trip links contain the countries, distances, consumption and fuel type you choose; anyone with the link can read those inputs. Do not include private information in shared URLs.",
    terms: "Display ads and affiliate recommendations are labelled and separated from editorial analysis. They cannot purchase a better fuel price or ranking. Rental quotes, availability, deposits, permissions, protection and payment are handled by the rental provider under its terms; a fuel estimate is not a rental quote or a booking.",
    independence: "We may earn from display ads and clearly disclosed rental referrals. Commercial revenue does not determine our data, coverage, rankings or conclusions. We do not sell sponsored fuel values or disguise paid promotions as independent analysis.",
    thirdParties: "Public data, maps, exchange rates, advertising and linked rental services are provided by third parties. We do not control their availability or practices. Fuel estimates exclude rental charges, parking, tolls and ferries; verify all booking conditions with the provider.",
  },
  sq: {
    about: "Karburanti Sot mirëmbahet në mënyrë të pavarur në Tiranë. Reklamat dhe lidhjet e etiketuara të partneritetit për udhëtime mund të financojnë shërbimin falas. Marrëveshjet tregtare nuk ndikojnë çmimet, renditjet ose përfundimet editoriale.",
    status: "Faqja mund të shfaqë reklama Google AdSense dhe lidhje të etiketuara për makina me qira kur janë konfiguruar. Zgjedhjet e pëlqimit menaxhohen nga shërbimi Privacy & messaging i Google. Mjetet e karburantit mbeten falas.",
    ads: "Google AdSense dhe partnerët mund të përdorin cookies ose identifikues pajisjeje për reklama dhe matje. Në faqet e përshtatshme në anglisht, hapësirat e reklamave presin konfirmimin nga shërbimi i certifikuar Privacy & messaging se zgjedhjet e pëlqimit janë gati. Google i zbaton ato në shfaqjen e reklamave, përfshirë kufizimet kur refuzon. Aty ku kërkohet, përfshirë ZEE, Mbretërinë e Bashkuar dhe Zvicrën, mesazhi lejon pranimin, refuzimin ose menaxhimin e opsioneve. Rihape nga cilësimet e privatësisë dhe cookies në fund të faqes. Bllokimi i shërbimit nga shfletuesi mund të pengojë reklamat. Metadata e verifikimit të publikuesit nuk ngarkon vetë skript reklamash.",
    analytics: "Kur aktivizohet, Cloudflare Web Analytics mat shikimet e faqeve, faqet referuese, vendet, pajisjet dhe performancën. Nuk shtojmë cookies analitike ose identifikues personalë. Bllokimi në shfletues dhe kampionimi mund të kufizojnë raportet. Cloudflare përpunon kërkesat sipas politikës së vet të privatësisë. Nuk mbledhim të dhëna pagese për qiranë dhe nuk mbajmë llogari klientësh.",
    affiliate: "Lidhjet e etiketuara DiscoverCars përmbajnë identifikues referimi dhe fushate. Kur klikon, ofruesi merr kërkesën dhe mund të përdorë cookies ose identifikues për atribuimin e rezervimit sipas kushteve të veta. Mund të marrim komision për qira të përfunduara dhe të shohim raportet e referimeve. Faqja jonë nuk ngarkon widget gjurmimi partneriteti. Lidhjet e udhëtimit përmbajnë vendet, distancat, konsumin dhe karburantin që zgjedh; kushdo me lidhjen mund t'i lexojë. Mos përfshi informacion privat në lidhjet e ndara.",
    terms: "Reklamat dhe rekomandimet e partneritetit janë të etiketuara dhe të ndara nga analiza. Nuk mund të blejnë çmim ose renditje më të favorshme. Ofertat, disponueshmëria, depozitat, lejet, mbulimi dhe pagesat menaxhohen nga ofruesi sipas kushteve të tij; vlerësimi i karburantit nuk është ofertë qiraje ose rezervim.",
    independence: "Mund të fitojmë nga reklamat dhe referimet e deklaruara të qirasë. Të ardhurat tregtare nuk përcaktojnë të dhënat, mbulimin, renditjet ose përfundimet. Nuk shesim vlera karburanti të sponsorizuara dhe nuk maskojmë promovime si analizë të pavarur.",
    thirdParties: "Të dhënat publike, hartat, kurset, reklamat dhe shërbimet e lidhura të qirasë ofrohen nga palë të treta. Nuk kontrollojmë disponueshmërinë ose praktikat e tyre. Vlerësimet e karburantit nuk përfshijnë qiranë, parkimin, tarifat rrugore dhe tragetet; verifiko kushtet me ofruesin.",
  },
};
