export const commercialCopy = {
  en: {
    about: "Karburanti Sot is maintained independently in Tirana. Display advertising and clearly labelled travel affiliate links may fund the free service. Commercial arrangements do not influence fuel prices, rankings, or editorial conclusions.",
    status: "This website may display a labelled Adsterra Native Banner on selected pages when site advertising is enabled and the visitor has allowed it. Rental affiliate links are separate and clearly disclosed. The fuel tools remain free to use.",
    ads: "Karburanti Sot may display advertising through Adsterra on selected pages. Advertising is optional: no Adsterra resource is requested until you explicitly allow advertising, and declining does not limit the website. If enabled, third-party advertising content and resources may be loaded from Adsterra or its delivery infrastructure and those providers may process technical request data or use browser technologies under their own terms. Change your choice at any time through Privacy & cookies in the footer. Browser blocking or unavailable inventory may prevent an ad from appearing.",
    analytics: "When enabled, Cloudflare Web Analytics measures page views, referring sites, countries, devices and page performance. We do not add analytics cookies or personal identifiers. Browser blocking and service sampling can limit these reports. Cloudflare processes requests under its own privacy policy. We do not collect rental payment details or operate a customer account system.",
    affiliate: "Labelled DiscoverCars links contain referral and campaign identifiers. If you click one, the provider receives the request and may use its own cookies or identifiers to attribute a booking under its privacy terms. We may receive a commission on eligible completed rentals and view referral and commission reports. No affiliate tracking widget is loaded on our website. Shared trip links contain the countries, distances, consumption and fuel type you choose; anyone with the link can read those inputs. Do not include private information in shared URLs.",
    terms: "Display ads and affiliate recommendations are labelled and separated from editorial analysis. They cannot purchase a better fuel price or ranking. Rental quotes, availability, deposits, permissions, protection and payment are handled by the rental provider under its terms; a fuel estimate is not a rental quote or a booking.",
    independence: "We may earn from display ads and clearly disclosed rental referrals. Commercial revenue does not determine our data, coverage, rankings or conclusions. We do not sell sponsored fuel values or disguise paid promotions as independent analysis.",
    thirdParties: "Public data, maps, exchange rates, advertising and linked rental services are provided by third parties. We do not control their availability or practices. Fuel estimates exclude rental charges, parking, tolls and ferries; verify all booking conditions with the provider.",
  },
  sq: {
    about: "Karburanti Sot mirëmbahet në mënyrë të pavarur në Tiranë. Reklamat dhe lidhjet e etiketuara të partneritetit për udhëtime mund të financojnë shërbimin falas. Marrëveshjet tregtare nuk ndikojnë çmimet, renditjet ose përfundimet editoriale.",
    status: "Faqja mund të shfaqë një Native Banner të etiketuar nga Adsterra në faqe të zgjedhura kur reklamat e faqes janë aktive dhe vizitori i ka lejuar. Lidhjet e partneritetit për qira janë të ndara dhe të deklaruara qartë. Mjetet e karburantit mbeten falas.",
    ads: "Karburanti Sot mund të shfaqë reklama përmes Adsterra në faqe të zgjedhura. Reklamat janë opsionale: nuk bëhet asnjë kërkesë te Adsterra pa lejen tënde të qartë dhe refuzimi nuk kufizon faqen. Kur aktivizohen, përmbajtje dhe burime reklamimi të palëve të treta mund të ngarkohen nga Adsterra ose infrastruktura e saj; këta ofrues mund të përpunojnë të dhëna teknike të kërkesës ose të përdorin teknologji të shfletuesit sipas kushteve të veta. Ndryshoje zgjedhjen në çdo kohë nga Privatësia & cookies në fund të faqes. Bllokimi në shfletues ose mungesa e inventarit mund të pengojë shfaqjen e reklamës.",
    analytics: "Kur aktivizohet, Cloudflare Web Analytics mat shikimet e faqeve, faqet referuese, vendet, pajisjet dhe performancën. Nuk shtojmë cookies analitike ose identifikues personalë. Bllokimi në shfletues dhe kampionimi mund të kufizojnë raportet. Cloudflare përpunon kërkesat sipas politikës së vet të privatësisë. Nuk mbledhim të dhëna pagese për qiranë dhe nuk mbajmë llogari klientësh.",
    affiliate: "Lidhjet e etiketuara DiscoverCars përmbajnë identifikues referimi dhe fushate. Kur klikon, ofruesi merr kërkesën dhe mund të përdorë cookies ose identifikues për atribuimin e rezervimit sipas kushteve të veta. Mund të marrim komision për qira të përfunduara dhe të shohim raportet e referimeve. Faqja jonë nuk ngarkon widget gjurmimi partneriteti. Lidhjet e udhëtimit përmbajnë vendet, distancat, konsumin dhe karburantin që zgjedh; kushdo me lidhjen mund t'i lexojë. Mos përfshi informacion privat në lidhjet e ndara.",
    terms: "Reklamat dhe rekomandimet e partneritetit janë të etiketuara dhe të ndara nga analiza. Nuk mund të blejnë çmim ose renditje më të favorshme. Ofertat, disponueshmëria, depozitat, lejet, mbulimi dhe pagesat menaxhohen nga ofruesi sipas kushteve të tij; vlerësimi i karburantit nuk është ofertë qiraje ose rezervim.",
    independence: "Mund të fitojmë nga reklamat dhe referimet e deklaruara të qirasë. Të ardhurat tregtare nuk përcaktojnë të dhënat, mbulimin, renditjet ose përfundimet. Nuk shesim vlera karburanti të sponsorizuara dhe nuk maskojmë promovime si analizë të pavarur.",
    thirdParties: "Të dhënat publike, hartat, kurset, reklamat dhe shërbimet e lidhura të qirasë ofrohen nga palë të treta. Nuk kontrollojmë disponueshmërinë ose praktikat e tyre. Vlerësimet e karburantit nuk përfshijnë qiranë, parkimin, tarifat rrugore dhe tragetet; verifiko kushtet me ofruesin.",
  },
};
