export const travelLabels = {
  en: {
    calculator: "Trip fuel cost calculator",
    guide: "Renting a car in Albania",
    openCalculator: "Calculate my trip",
    openGuide: "Read the rental guide",
    related: "Plan the next step",
    calculatorCardEyebrow: "Route lab / live prices",
    calculatorCardText: "Build a country-by-country fuel budget with distance, consumption, and today's reference prices.",
    calculatorCardCta: "Open trip calculator",
    guideCardEyebrow: "Albania / driver briefing",
    guideCardText: "Know the deposit, fuel policy, cross-border questions, and driving costs before you book.",
    guideCardCta: "Read the guide",
    privacy: "Privacy and cookie settings",
    privacyUnavailable: "Advertising settings are unavailable here, or your browser has blocked the consent service. Read our privacy policy for details.",
  },
  sq: {
    calculator: "Llogaritësi i kostos së karburantit",
    guide: "Marrja e një makine me qira në Shqipëri",
    openCalculator: "Llogarit udhëtimin",
    openGuide: "Lexo udhëzuesin e qirasë",
    related: "Planifiko hapin tjetër",
    calculatorCardEyebrow: "Laboratori i rrugës / çmime aktuale",
    calculatorCardText: "Ndërto një buxhet karburanti sipas shtetit me distancën, konsumin dhe çmimet orientuese të sotme.",
    calculatorCardCta: "Hap llogaritësin",
    guideCardEyebrow: "Shqipëri / udhëzues për shoferin",
    guideCardText: "Mëso për depozitën, politikën e karburantit, kalimin e kufirit dhe kostot e drejtimit para rezervimit.",
    guideCardCta: "Lexo udhëzuesin",
    privacy: "Cilësimet e privatësisë dhe cookies",
    privacyUnavailable: "Cilësimet e reklamave nuk janë të disponueshme këtu, ose shfletuesi bllokon shërbimin e pëlqimit. Lexo politikën tonë të privatësisë.",
  },
};
