import { StyleSheet } from "react-native";
import type { Theme } from "../theme/theme";

export const makeRankingsTabStyles = (theme: Theme) => StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.colors.bg },
  listContent: { width: "100%", maxWidth: theme.m.maxContentWidth, alignSelf: "center", padding: theme.m.gutter, paddingBottom: theme.m.s(32) },
  headerContent: { gap: theme.m.s(14), marginBottom: theme.m.s(12) },
  snapshot: { padding: theme.m.s(17), borderRadius: 28, gap: 15, backgroundColor: theme.name === "light" ? "#EEF3FA" : "#111F36", borderWidth: 1, borderColor: theme.colors.border },
  snapshotTop: { flexDirection: theme.m.isLargeText ? "column" : "row", alignItems: theme.m.isLargeText ? "stretch" : "center", gap: 12 },
  snapshotCopy: { flex: 1, minWidth: 0 },
  snapshotKicker: { color: theme.colors.info, fontSize: theme.m.f(10), fontWeight: "900", textTransform: "uppercase", letterSpacing: 1 },
  snapshotTitle: { marginTop: 5, color: theme.colors.text, fontSize: theme.m.f(23), lineHeight: theme.m.f(29), fontWeight: "900" },
  snapshotPrice: { alignItems: theme.m.isLargeText ? "flex-start" : "flex-end" },
  snapshotPriceText: { color: theme.colors.text, fontSize: theme.m.f(20), fontWeight: "900" },
  snapshotPriceSub: { marginTop: 3, color: theme.colors.muted, fontSize: theme.m.f(10), fontWeight: "800" },
  metrics: { flexDirection: theme.m.isLargeText ? "column" : "row", gap: 8 },
  metric: { flex: 1, minHeight: 67, justifyContent: "space-between", padding: 10, borderRadius: 17, backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  metricValue: { color: theme.colors.text, fontSize: theme.m.f(14), fontWeight: "900" },
  metricLabel: { color: theme.colors.muted, fontSize: theme.m.f(9), fontWeight: "800" },
  good: { color: theme.colors.success },
  warning: { color: theme.colors.warning },
  yourPosition: { minHeight: 57, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, paddingTop: 12, borderTopWidth: 1, borderTopColor: theme.colors.border },
  yourCopy: { flex: 1, minWidth: 0 },
  yourLabel: { color: theme.colors.muted, fontSize: theme.m.f(9), fontWeight: "900", textTransform: "uppercase", letterSpacing: 0.8 },
  yourCountry: { marginTop: 3, color: theme.colors.text, fontSize: theme.m.f(13), fontWeight: "900" },
  rankPill: { minHeight: 40, flexDirection: "row", alignItems: "baseline", gap: 3, paddingHorizontal: 13, borderRadius: 999, backgroundColor: theme.colors.accentSoft },
  rankPillText: { color: theme.colors.primary, fontSize: theme.m.f(16), fontWeight: "900" },
  rankPillSub: { color: theme.colors.muted, fontSize: theme.m.f(10), fontWeight: "800" },
  favoriteState: { minHeight: 84, flexDirection: "row", alignItems: "center", gap: 11, padding: 13, borderRadius: 21, backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  favoriteIcon: { width: 46, height: 46, borderRadius: 17, alignItems: "center", justifyContent: "center", backgroundColor: theme.colors.accentSoft },
  favoriteCopy: { flex: 1, minWidth: 0 },
  favoriteTitle: { color: theme.colors.text, fontSize: theme.m.f(13), fontWeight: "900" },
  favoriteText: { marginTop: 3, color: theme.colors.muted, fontSize: theme.m.f(10), lineHeight: theme.m.f(14), fontWeight: "700" },
  manageButton: { width: 48, height: 48, borderRadius: 17, alignItems: "center", justifyContent: "center", backgroundColor: theme.colors.surfaceMuted },
  modeRow: { flexDirection: "row", gap: 8, padding: 4, borderRadius: 19, backgroundColor: theme.colors.surfaceMuted },
  modeItem: { flex: 1 },
  modeButton: { minHeight: 48, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, paddingHorizontal: 8, borderRadius: 15 },
  modeActive: { backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  modeText: { color: theme.colors.muted, fontSize: theme.m.f(11), fontWeight: "900" },
  modeTextActive: { color: theme.colors.primary },
  sectionTitle: { marginBottom: 9, color: theme.colors.text, fontSize: theme.m.f(15), fontWeight: "900" },
  podium: { flexDirection: "row", gap: 8 },
  podiumItem: { flex: 1 },
  podiumCard: { minHeight: 126, alignItems: "center", padding: 10, borderRadius: 20, backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  podiumFirst: { backgroundColor: theme.name === "light" ? "#FFF8E7" : "#2B261B", borderColor: theme.name === "light" ? "rgba(180,83,9,0.20)" : "rgba(251,191,36,0.20)" },
  medal: { width: 29, height: 29, borderRadius: 11, alignItems: "center", justifyContent: "center" },
  medalGold: { backgroundColor: "rgba(245,158,11,0.22)" },
  medalSilver: { backgroundColor: "rgba(148,163,184,0.22)" },
  medalBronze: { backgroundColor: "rgba(180,83,9,0.15)" },
  medalText: { color: theme.colors.text, fontSize: theme.m.f(10), fontWeight: "900" },
  podiumFlag: { marginTop: 7, fontSize: 23 },
  podiumCountry: { marginTop: 5, width: "100%", color: theme.colors.text, fontSize: theme.m.f(10), fontWeight: "900", textAlign: "center" },
  podiumPrice: { marginTop: 5, color: theme.colors.primary, fontSize: theme.m.f(11), fontWeight: "900" },
  row: { minHeight: 70, flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 21, backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  rowActive: { backgroundColor: theme.colors.accentSoft, borderColor: theme.colors.primary },
  rowRank: { width: 40, height: 40, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: theme.colors.surfaceMuted },
  rowRankTop: { backgroundColor: theme.colors.accentSoft },
  rowRankText: { color: theme.colors.text, fontSize: theme.m.f(12), fontWeight: "900" },
  rowCopy: { flex: 1, minWidth: 0 },
  rowCountry: { color: theme.colors.text, fontSize: theme.m.f(13), fontWeight: "900" },
  badges: { marginTop: 3, flexDirection: "row", gap: 5 },
  badge: { color: theme.colors.primary, fontSize: theme.m.f(9), fontWeight: "900" },
  rowPrice: { alignItems: "flex-end" },
  rowPriceText: { color: theme.colors.text, fontSize: theme.m.f(13), fontWeight: "900" },
  rowDelta: { marginTop: 4, color: theme.colors.muted, fontSize: theme.m.f(9), fontWeight: "800" },
  deltaUp: { color: theme.colors.danger },
  deltaDown: { color: theme.colors.success },
  pinned: { marginTop: 18, gap: 8, paddingTop: 15, borderTopWidth: 1, borderTopColor: theme.colors.border },
  pinnedLabel: { color: theme.colors.text, fontSize: theme.m.f(14), fontWeight: "900" },
  empty: { padding: 25, borderRadius: 22, backgroundColor: theme.colors.surfaceRaised },
  emptyText: { color: theme.colors.muted, fontSize: theme.m.f(13), fontWeight: "700", textAlign: "center" },
  footerSpace: { height: 18 },
});
