import { StyleSheet } from "react-native";
import type { Theme } from "../theme/theme";

export const makeSettingsStyles = (theme: Theme) => StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.colors.bg },
  container: { width: "100%", maxWidth: theme.m.maxContentWidth, alignSelf: "center", padding: theme.m.gutter, paddingBottom: theme.m.s(34), gap: theme.m.s(17) },
  appearanceCard: { padding: theme.m.s(17), borderRadius: 28, gap: 16, backgroundColor: theme.name === "light" ? "#F4EFE5" : "#18202D", borderWidth: 1, borderColor: theme.colors.border },
  appearanceHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  cardKicker: { color: theme.colors.primary, fontSize: theme.m.f(10), fontWeight: "900", textTransform: "uppercase", letterSpacing: 1 },
  cardTitle: { marginTop: 5, color: theme.colors.text, fontSize: theme.m.f(21), fontWeight: "900" },
  appearanceIcon: { width: 57, height: 57, borderRadius: 22, alignItems: "center", justifyContent: "center", backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  themeOptions: { flexDirection: theme.m.isLargeText ? "column" : "row", gap: 8, padding: 4, borderRadius: 20, backgroundColor: theme.colors.surfaceMuted },
  themeItem: { flex: 1 },
  themeButton: { minHeight: 50, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, paddingHorizontal: 8, borderRadius: 16 },
  themeButtonActive: { backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  themeText: { color: theme.colors.muted, fontSize: theme.m.f(11), fontWeight: "900" },
  themeTextActive: { color: theme.colors.primary },
  sectionTitle: { marginBottom: 8, marginLeft: 5, color: theme.colors.muted, fontSize: theme.m.f(10), fontWeight: "900", letterSpacing: 1, textTransform: "uppercase" },
  section: { overflow: "hidden", borderRadius: 24, backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  row: { minHeight: 76, flexDirection: "row", alignItems: "center", gap: 11, paddingHorizontal: 13, paddingVertical: 10 },
  rowIcon: { width: 44, height: 44, borderRadius: 16, alignItems: "center", justifyContent: "center" },
  rowCopy: { flex: 1, minWidth: 0 },
  rowLabel: { color: theme.colors.text, fontSize: theme.m.f(14), fontWeight: "900" },
  rowDetail: { marginTop: 3, color: theme.colors.muted, fontSize: theme.m.f(10), lineHeight: theme.m.f(14), fontWeight: "700" },
  rowValue: { maxWidth: 86, color: theme.colors.primary, fontSize: theme.m.f(11), fontWeight: "900", textAlign: "right" },
  divider: { height: 1, marginLeft: 68, backgroundColor: theme.colors.border },
  dataCard: { padding: theme.m.s(16), borderRadius: 26, gap: 14, backgroundColor: theme.name === "light" ? "#EAF5F2" : "#0D3034", borderWidth: 1, borderColor: theme.name === "light" ? "rgba(15,118,110,0.14)" : "rgba(45,212,191,0.18)" },
  dataHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  dataTitleRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  healthDot: { width: 11, height: 11, borderRadius: 6 },
  dataStatus: { marginTop: 3, color: theme.colors.text, fontSize: theme.m.f(18), fontWeight: "900" },
  refreshButton: { width: 48, height: 48, borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  dataRows: { overflow: "hidden", borderRadius: 18, backgroundColor: theme.colors.surfaceRaised },
  dataRow: { minHeight: 51, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, paddingHorizontal: 13, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: theme.colors.border },
  dataLabel: { color: theme.colors.muted, fontSize: theme.m.f(10), fontWeight: "800" },
  dataValue: { flex: 1, color: theme.colors.text, fontSize: theme.m.f(11), lineHeight: theme.m.f(15), fontWeight: "800", textAlign: "right" },
  sourceButton: { minHeight: 48, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, borderRadius: 17, backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  sourceButtonText: { color: theme.colors.text, fontSize: theme.m.f(12), fontWeight: "900" },
  footer: { alignItems: "center", paddingVertical: 18, gap: 4 },
  footerBrand: { color: theme.colors.text, fontSize: theme.m.f(12), fontWeight: "900" },
  footerVersion: { color: theme.colors.muted, fontSize: theme.m.f(10), fontWeight: "700" },
  sheetOptions: { gap: 9, paddingBottom: 5 },
  sheetOption: { minHeight: 68, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, paddingHorizontal: 14, borderRadius: 20, backgroundColor: theme.colors.surfaceMuted, borderWidth: 1, borderColor: theme.colors.border },
  sheetSelected: { backgroundColor: theme.colors.accentSoft, borderColor: theme.colors.primary },
  sheetOptionCopy: { flex: 1, minWidth: 0 },
  sheetOptionLabel: { color: theme.colors.text, fontSize: theme.m.f(14), fontWeight: "900" },
  sheetOptionDetail: { marginTop: 3, color: theme.colors.muted, fontSize: theme.m.f(11), fontWeight: "700" },
  disabled: { opacity: 0.42 },
});
