import { StyleSheet } from "react-native";
import type { Theme } from "../theme/theme";

export const makeStationsTabStyles = (theme: Theme) => StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.colors.bg },
  listContent: { width: "100%", maxWidth: theme.m.maxContentWidth, alignSelf: "center", padding: theme.m.gutter, paddingBottom: theme.m.s(32) },
  headerContent: { gap: theme.m.s(14), marginBottom: theme.m.s(14) },
  headerAction: { width: 48, height: 48, borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  hero: { minHeight: 138, padding: theme.m.s(18), borderRadius: 28, flexDirection: "row", alignItems: "center", overflow: "hidden", backgroundColor: theme.name === "light" ? "#E8F5F1" : "#0D3536", borderWidth: 1, borderColor: theme.name === "light" ? "rgba(15,118,110,0.14)" : "rgba(45,212,191,0.20)" },
  heroCopy: { flex: 1, minWidth: 0 },
  heroKicker: { color: theme.colors.primary, fontSize: theme.m.f(10), fontWeight: "900", textTransform: "uppercase", letterSpacing: 1 },
  heroTitle: { marginTop: 6, color: theme.colors.text, fontSize: theme.m.f(25), lineHeight: theme.m.f(30), fontWeight: "900" },
  statusRow: { marginTop: 12, flexDirection: "row", alignItems: "center", gap: 7 },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  statusText: { color: theme.colors.subText, fontSize: theme.m.f(12), fontWeight: "800" },
  heroMark: { width: 72, height: 72, borderRadius: 28, alignItems: "center", justifyContent: "center", backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  metrics: { flexDirection: theme.m.isLargeText ? "column" : "row", gap: theme.m.s(9) },
  metric: { flex: 1, minHeight: 76, padding: theme.m.s(12), borderRadius: 20, justifyContent: "space-between", backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  metricValue: { color: theme.colors.text, fontSize: theme.m.f(18), fontWeight: "900" },
  metricLabel: { color: theme.colors.muted, fontSize: theme.m.f(11), fontWeight: "800" },
  searchWrap: { minHeight: 52, flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 15, borderRadius: 20, backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  searchInput: { flex: 1, minWidth: 0, color: theme.colors.text, fontSize: theme.m.f(14), fontWeight: "700" },
  clearSearch: { width: 44, height: 44, alignItems: "center", justifyContent: "center" },
  filterRow: { flexDirection: "row", gap: theme.m.s(8), flexWrap: "wrap" },
  filterChip: { minHeight: 48, flexDirection: "row", alignItems: "center", gap: 7, paddingHorizontal: 13, borderRadius: 999, backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  filterChipActive: { backgroundColor: theme.colors.accentSoft, borderColor: theme.colors.primary },
  filterText: { color: theme.colors.muted, fontSize: theme.m.f(12), fontWeight: "800" },
  filterTextActive: { color: theme.colors.primary },
  resultHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 2 },
  resultTitle: { color: theme.colors.text, fontSize: theme.m.f(17), fontWeight: "900" },
  resultSub: { marginTop: 3, color: theme.colors.muted, fontSize: theme.m.f(11), fontWeight: "700" },
  textButton: { minHeight: 48, justifyContent: "center", paddingHorizontal: 8 },
  textButtonLabel: { color: theme.colors.primary, fontSize: theme.m.f(12), fontWeight: "900" },
  stationCard: { padding: theme.m.s(14), borderRadius: 22, gap: theme.m.s(13), backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border, shadowColor: "#000", shadowOpacity: theme.name === "light" ? 0.05 : 0.18, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 2 },
  stationTop: { flexDirection: "row", alignItems: "center", gap: 11 },
  stationPin: { width: 44, height: 44, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: theme.colors.accentSoft },
  stationCopy: { flex: 1, minWidth: 0 },
  stationName: { color: theme.colors.text, fontSize: theme.m.f(15), fontWeight: "900" },
  stationBrand: { marginTop: 3, color: theme.colors.muted, fontSize: theme.m.f(11), fontWeight: "700" },
  favoriteButton: { width: 48, height: 48, alignItems: "center", justifyContent: "center", borderRadius: 18, backgroundColor: theme.colors.pillBg },
  stationBottom: { minHeight: 48, flexDirection: theme.m.isLargeText ? "column" : "row", alignItems: theme.m.isLargeText ? "stretch" : "center", justifyContent: "space-between", gap: 10, paddingTop: 10, borderTopWidth: 1, borderTopColor: theme.colors.border },
  stationMeta: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 6 },
  openDot: { width: 7, height: 7, borderRadius: 4 },
  stationStatus: { color: theme.colors.subText, fontSize: theme.m.f(11), fontWeight: "800" },
  metaDivider: { color: theme.colors.muted },
  stationDistance: { color: theme.colors.muted, fontSize: theme.m.f(11), fontWeight: "800" },
  directionsButton: { minHeight: 48, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, paddingHorizontal: 14, borderRadius: 17, backgroundColor: theme.colors.primary },
  directionsText: { color: theme.colors.primaryText, fontSize: theme.m.f(12), fontWeight: "900" },
  stateCard: { alignItems: "center", padding: theme.m.s(24), borderRadius: 26, backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  loadingState: { minHeight: 160, alignItems: "center", justifyContent: "center", gap: 10, borderRadius: 26, backgroundColor: theme.colors.surfaceRaised, borderWidth: 1, borderColor: theme.colors.border },
  stateIcon: { width: 58, height: 58, borderRadius: 22, alignItems: "center", justifyContent: "center", backgroundColor: theme.colors.accentSoft },
  stateTitle: { marginTop: 14, color: theme.colors.text, fontSize: theme.m.f(18), fontWeight: "900", textAlign: "center" },
  stateMessage: { marginTop: 7, color: theme.colors.muted, fontSize: theme.m.f(13), lineHeight: theme.m.f(19), fontWeight: "700", textAlign: "center" },
  stateButton: { marginTop: 17, minHeight: 50, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, paddingHorizontal: 18, borderRadius: 18, backgroundColor: theme.colors.primary },
  stateButtonText: { color: theme.colors.primaryText, fontSize: theme.m.f(13), fontWeight: "900" },
  error: { marginTop: 14, flexDirection: "row", alignItems: "flex-start", gap: 9, padding: 13, borderRadius: 18, backgroundColor: theme.colors.surfaceMuted },
  errorText: { flex: 1, color: theme.colors.warning, fontSize: theme.m.f(12), lineHeight: theme.m.f(17), fontWeight: "700" },
  footerSpace: { height: 16 },
  radiusList: { gap: 9, paddingBottom: 4 },
  radiusOption: { minHeight: 68, flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 13, borderRadius: 20, backgroundColor: theme.colors.surfaceMuted, borderWidth: 1, borderColor: theme.colors.border },
  radiusOptionActive: { backgroundColor: theme.colors.accentSoft, borderColor: theme.colors.primary },
  radiusIcon: { width: 42, height: 42, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: theme.colors.surfaceRaised },
  radiusTitle: { color: theme.colors.text, fontSize: theme.m.f(14), fontWeight: "900" },
  radiusSub: { marginTop: 3, color: theme.colors.muted, fontSize: theme.m.f(11), fontWeight: "700" },
});
