import { StyleSheet } from "react-native";
import type { Theme } from "../../theme/theme";

export const makeCountryModalStyles = (theme: Theme) =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: theme.colors.overlay,
      justifyContent: "flex-end",
    },
    backdrop: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0 },
    sheet: {
      backgroundColor: theme.colors.surfaceRaised,
      borderTopLeftRadius: theme.radius.xl,
      borderTopRightRadius: theme.radius.xl,
      padding: theme.m.s(18),
      borderTopWidth: 1,
      borderColor: theme.colors.border,
      maxHeight: "88%",
    },
    flag: { fontSize: 20 },
    rowCopy: { flex: 1, minWidth: 0, gap: 2 },
    rowTextMuted: { color: theme.colors.muted },
    empty: { padding: theme.m.s(18), color: theme.colors.muted, fontSize: theme.m.f(14), fontWeight: "700", textAlign: "center" },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: theme.m.s(12),
      marginBottom: theme.m.s(10),
    },
    title: {
      flex: 1,
      fontSize: theme.m.f(19),
      fontWeight: "900",
      color: theme.colors.text,
    },
    closeBtn: {
      minHeight: 48,
      justifyContent: "center",
      paddingVertical: theme.m.s(8),
      paddingHorizontal: theme.m.s(12),
      borderRadius: 12,
      backgroundColor: theme.colors.pillBg,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    closeText: {
      fontSize: theme.m.f(13),
      fontWeight: "800",
      color: theme.colors.text,
    },
    input: {
      minHeight: 48,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 14,
      paddingHorizontal: theme.m.s(12),
      paddingVertical: theme.m.s(10),
      color: theme.colors.text,
      backgroundColor: theme.colors.card,
      marginBottom: theme.m.s(10),
      fontSize: theme.m.f(15),
      fontWeight: "600",
    },
    list: {
      flexShrink: 1,
      borderRadius: 14,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.card,
    },
    row: {
      minHeight: 56,
      paddingVertical: theme.m.s(12),
      paddingHorizontal: theme.m.s(12),
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: theme.m.s(10),
    },
    rowText: {
      color: theme.colors.text,
      fontSize: theme.m.f(15),
      fontWeight: "700",
    },
    starBtn: {
      width: 48,
      height: 48,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 10,
      backgroundColor: theme.colors.pillBg,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    starText: {
      fontSize: theme.m.f(14),
      fontWeight: "900",
    },
    starOn: {
      color: theme.colors.text,
    },
    starOff: {
      color: theme.colors.muted,
    },
    badgeText: {
      color: theme.colors.subText,
      fontWeight: "800",
      fontSize: theme.m.f(12),
    },
  });
