import { useEffect } from "react";
import { Link } from "react-router-dom";
import type { TDict } from "../locales";

type Props = { t: TDict };

export default function DisclaimerPage({ t }: Props) {
  useEffect(() => { window.scrollTo(0, 0); }, []);

  return (
    <article className="contentPage">
      <h1 className="contentPageTitle">Disclaimer</h1>
      <p className="contentBody">
        Last updated: June 2026
      </p>
      <p className="contentBody">
        The information published on Karburanti Sot (karburantisot.com) is provided
        for general informational and reference purposes only. By using this website,
        you acknowledge and agree to the limitations described on this page.
      </p>

      <section className="contentSection">
        <h2 className="contentHeading">Fuel price data is informational only</h2>
        <p className="contentBody">
          The fuel prices displayed on this site are sourced from publicly available
          third-party datasets and are intended as broad reference values. They do not
          represent the exact price you will be charged at any specific fuel station,
          at any specific time, or in any specific local area.
        </p>
        <p className="contentBody">
          Country-level figures are national averages or reference values from public
          data sources. Actual pump prices at individual stations can differ from these
          figures due to local competition, brand pricing, promotional rates, regional
          taxes, time-of-day pricing, and the timing of the station's last wholesale
          delivery. You should verify prices directly with the station before making
          fueling decisions that depend on price accuracy.
        </p>
      </section>

      <section className="contentSection">
        <h2 className="contentHeading">No financial or commercial advice</h2>
        <p className="contentBody">
          Nothing on this website constitutes financial advice, investment advice, or
          commercial guidance. Exchange-rate conversions shown on the site use public
          FX data and are indicative estimates only — they are not bank rates, trading
          rates, or guaranteed conversion values. Do not use this site for currency
          trading, financial planning, or business cost modeling purposes.
        </p>
        <p className="contentBody">
          Trip cost estimates generated by the tools on this site are approximate
          calculations based on the fuel price data in the system at the time of the
          calculation, a user-supplied consumption figure, and a user-supplied
          distance. They are estimates for planning purposes only. Actual fuel costs
          will vary.
        </p>
      </section>

      <section className="contentSection">
        <h2 className="contentHeading">Data accuracy and timeliness</h2>
        <p className="contentBody">
          We make reasonable efforts to keep the data on this site accurate and
          up-to-date. However, we cannot guarantee the accuracy, completeness, or
          timeliness of any information displayed. Data from upstream sources may
          contain errors, be subject to reporting delays, or become temporarily
          unavailable. The "last updated" timestamp shown in the tool reflects when
          the dataset was last successfully fetched, not when prices were last verified
          at individual stations.
        </p>
        <p className="contentBody">
          Fuel markets can change rapidly in response to crude oil movements,
          government decisions, exchange-rate shifts, or seasonal demand. A price shown
          today may not reflect the price you encounter when you travel. Always check
          current conditions before a trip, especially for longer or multi-country
          routes.
        </p>
      </section>

      <section className="contentSection">
        <h2 className="contentHeading">Limitation of liability</h2>
        <p className="contentBody">
          To the fullest extent permitted by applicable law, Karburanti Sot, its
          operator, and its contributors shall not be liable for any loss, damage,
          injury, or expense of any kind arising from:
        </p>
        <ul className="contentList">
          <li>Reliance on the fuel price data, estimates, or comparisons on this site</li>
          <li>Decisions made about refueling, travel planning, or route planning based on information from this site</li>
          <li>Any inaccuracy, omission, or delay in the data displayed</li>
          <li>Interruptions in data availability due to upstream source changes or technical issues</li>
          <li>Use of the trip calculator, comparison tools, or any other feature of the site</li>
        </ul>
        <p className="contentBody">
          The site is provided "as is" and "as available" without warranties of any
          kind, express or implied, including but not limited to warranties of
          merchantability, fitness for a particular purpose, or non-infringement.
        </p>
      </section>

      <section className="contentSection">
        <h2 className="contentHeading">Third-party links and services</h2>
        <p className="contentBody">
          This site may link to third-party websites including fuel data sources,
          mapping providers, and other external references. These links are provided
          for convenience and information only. Karburanti Sot does not endorse, control,
          or take responsibility for the content, accuracy, or practices of any
          third-party website. Visiting linked sites is at your own risk.
        </p>
        <p className="contentBody">
          The site uses third-party advertising services (Google AdSense and Google
          AdMob). These services may collect data as described in the{" "}
          <Link to="/privacy" className="inlineLink">{t.navPrivacy}</Link>. We are not
          responsible for the content of third-party advertisements.
        </p>
      </section>

      <section className="contentSection">
        <h2 className="contentHeading">Nearby station data</h2>
        <p className="contentBody">
          The nearby stations feature uses location data from your device (with your
          permission) and map/location APIs to display fuel stations near you. Station
          data — including opening hours, prices, and availability — comes from
          third-party sources and may be incomplete, outdated, or inaccurate. Do not
          rely solely on the station information shown to determine whether a specific
          station is open, operational, or offering a particular fuel type.
        </p>
      </section>

      <section className="contentSection">
        <h2 className="contentHeading">Changes to this disclaimer</h2>
        <p className="contentBody">
          This Disclaimer may be updated from time to time. When updated, the "last
          updated" date at the top of this page will be revised. Continued use of the
          site after any update constitutes acceptance of the revised Disclaimer.
        </p>
      </section>

      <section className="contentSection">
        <h2 className="contentHeading">Contact</h2>
        <p className="contentBody">
          If you have questions about this Disclaimer, please contact us at{" "}
          <a href="mailto:fenixkola@gmail.com" className="inlineLink">fenixkola@gmail.com</a>{" "}
          or through the <Link to="/contact" className="inlineLink">{t.navContact}</Link> page.
        </p>
      </section>
    </article>
  );
}
