import { Link } from "react-router-dom";
import type { TDict } from "../locales";
import type { LatestEurope, FuelType } from "../models/fuel";
import type { Currency } from "../models/currency";
import type { FxRates } from "../utils/currency";
import RankingCard from "../components/fuel/RankingCard";

type Props = {
  t: TDict;
  data: LatestEurope | null;
  fuelType: FuelType;
  setFuelType: (v: FuelType) => void;
  currency: Currency;
  fxRates: FxRates | null;
  onOpen: (country: string) => void;
};

export default function RankingsPage({
  t,
  data,
  fuelType,
  setFuelType,
  currency,
  fxRates,
  onOpen,
}: Props) {
  return (
    <>
      <div className="pageHeader">
        <h1 className="pageHeaderTitle">{t.navRankings}</h1>
        <p className="pageHeaderSub">{t.rankingsGuidance}</p>
      </div>
      <RankingCard
        t={t}
        data={data}
        fuelType={fuelType}
        setFuelType={setFuelType}
        currency={currency}
        fxRates={fxRates}
        onOpen={onOpen}
      />

      <article className="contentPage">
        <section className="contentSection">
          <h2 className="contentHeading">{t.rankingsEditorialTitle}</h2>
          <p className="contentBody">{t.rankingsEditorialP1}</p>
          <p className="contentBody">{t.rankingsEditorialP2}</p>
          <p className="contentBody">{t.rankingsEditorialP3}</p>
          <p className="contentBody">{t.rankingsEditorialP4}</p>
        </section>

        <section className="contentSection">
          <h2 className="contentHeading">How rankings are calculated</h2>
          <p className="contentBody">
            Rankings on this page are generated by sorting all covered countries by their reported fuel price for the selected fuel type (petrol, diesel, or LPG). Prices are expressed in EUR per liter to allow direct comparison across eurozone and non-eurozone markets. For countries using local currencies (Albania/ALL, UK/GBP, Switzerland/CHF, North Macedonia/MKD), prices are converted to EUR using mid-market exchange rates from a public FX source.
          </p>
          <p className="contentBody">
            The ranking algorithm is straightforward: lower EUR/L price = higher rank (cheaper). Countries with missing or unavailable data for a specific fuel type are excluded from that ranking. This means the number of ranked countries may differ between petrol, diesel, and LPG views.
          </p>
        </section>

        <section className="contentSection">
          <h2 className="contentHeading">Why rankings change over time</h2>
          <p className="contentBody">
            Fuel price rankings are not static. They shift due to several factors: changes in international crude oil prices affect all countries but at different speeds depending on local supply chains; government interventions (subsidy introductions, excise adjustments, price caps) can move a country up or down rapidly; exchange-rate movements change the EUR-equivalent price for non-eurozone countries even when local prices are unchanged; and seasonal demand patterns create temporary shifts.
          </p>
          <p className="contentBody">
            For example, Albania might rank differently in summer (when tourism increases fuel demand) versus winter. A country that introduces a temporary fuel subsidy may jump several positions lower in the ranking, only to return to its previous position when the subsidy expires.
          </p>
        </section>

        <section className="contentSection">
          <h2 className="contentHeading">How tax, FX, and source timing affect what you see</h2>
          <p className="contentBody">
            Tax policy is the dominant factor in cross-country rankings. Countries with high excise duties (Netherlands, Finland, Italy) consistently rank near the top (most expensive), while countries with lower taxation (Kosovo, Poland, Bulgaria) rank near the bottom (cheapest). The tax component can account for 40–60% of the pump price in high-tax countries.
          </p>
          <p className="contentBody">
            Exchange-rate effects matter for non-Euro countries. If the Albanian Lek weakens against the Euro, Albania&apos;s fuel appears cheaper in EUR terms even if the Lek price hasn&apos;t changed. Similarly, GBP/EUR movements affect the UK&apos;s ranking position.
          </p>
          <p className="contentBody">
            Source update timing creates temporary ranking anomalies. If one country&apos;s data updated today and another&apos;s was last updated five days ago, the comparison reflects different market moments. The &quot;last updated&quot; timestamp helps users assess data freshness.
          </p>
        </section>

        <section className="contentSection">
          <h2 className="contentHeading">Related tools and guides</h2>
          <ul className="contentList">
            <li><Link className="inlineLink" to="/compare">Compare specific countries</Link> — build a watchlist for targeted comparisons</li>
            <li><Link className="inlineLink" to="/europe-fuel-comparison">Europe fuel comparison guide</Link> — understand regional patterns</li>
            <li><Link className="inlineLink" to="/how-fuel-prices-work">How fuel prices work</Link> — crude oil to pump price chain</li>
            <li><Link className="inlineLink" to="/methodology">Methodology</Link> — data sources and processing details</li>
          </ul>
        </section>
      </article>
    </>
  );
}
